import fs from 'node:fs';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
const read=p=>JSON.parse(fs.readFileSync('../'+p,'utf8'));
const manifest=read('research/public_expansion_v1/manifest.json');
const candidates=read('research/dataset_audit_v1/candidates.json');
const audit=read('research/dataset_audit_v1/existing_results.json');
assert.equal(manifest.version,1);assert.equal(candidates.schema_version,1);assert(audit.datasets);
const files=['research/dataset_audit_v1/existing_results.json','research/dataset_audit_v1/candidates.json','research/public_expansion_v1/manifest.json','research/public_expansion_v1/audit.json'];
const review={version:1,date:candidates.reviewed_at,datasets:['clinc150','banking77'].map(id=>({id,label:id==='clinc150'?'CLINC150 + OOS':'BANKING77',full:manifest.suites[id+'_full'].n,classes:manifest.suites[id+'_full'].classes,clean:manifest.suites[id+'_exact_clean'].n,pilot:manifest.suites[id+'_pilot'].n,license:manifest.licenses[id],status:'prepared_not_evaluated',score:null})),models:candidates.models.filter(m=>m.priority<=2).map(m=>({id:m.id,label:m.label,repo:m.repo,revision:m.revision,license:m.license,score:null})),sources:files.map(path=>({path,sha256:crypto.createHash('sha256').update(fs.readFileSync('../'+path)).digest('hex')}))};
fs.writeFileSync('data/review.json',JSON.stringify(review,null,2)+'\n');
console.log('Prepared source-bound audit registry: two datasets; pending models have no scores');
