const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const filters={all:'全部图表',models:'模型比较',data:'数据与任务'};
const actions=f=>`<div class="figure-actions"><button class="figure-open" data-figure="${esc(f.id)}">放大查看 <span aria-hidden="true">↗</span></button><a href="${esc(f.assets.svg)}" download>SVG</a><a href="${esc(f.assets.pdf)}" download>PDF</a><a href="${esc(f.source)}" target="_blank" rel="noopener">数据来源</a></div>`;
const table=f=>`<details class="figure-data"><summary>查看精确数值与统计口径</summary><p>${esc(f.definition)}</p><div class="figure-table-scroll"><table><caption class="sr-only">${esc(f.title)}的数值</caption><thead><tr>${f.columns.map(c=>`<th scope="col">${esc(c)}</th>`).join('')}</tr></thead><tbody>${f.rows.map(row=>`<tr>${row.map((c,i)=>i===0?`<th scope="row">${esc(c)}</th>`:`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div></details>`;
export function figureDetailMarkup(f){return `<p class="figure-description">${esc(f.description)}</p><div class="figure-zoom-controls" role="group" aria-label="图表缩放"><button data-figure-zoom="fit" aria-pressed="true">适应窗口</button><button data-figure-zoom="150" aria-pressed="false">150%</button><button data-figure-zoom="200" aria-pressed="false">200%</button></div><div class="figure-zoom-stage"><img class="figure-full" src="${esc(f.assets.svg)}" alt="${esc(f.alt)}"></div><p class="figure-caveat">${esc(f.caveat)}</p>${actions(f)}${table(f)}`;}
export function previewMarkup(data){const featured=data.figures.filter(f=>['profiles','lengths','taxonomy'].includes(f.id));return `<div class="paper-preview-heading"><div><span class="section-kicker">RESEARCH AT A GLANCE</span><h2>论文图表</h2><p>领域成绩、输入结构与评测框架。</p></div><button data-view="paper">查看全部图表 <span aria-hidden="true">→</span></button></div><div class="paper-preview-grid">${featured.map(f=>`<button class="paper-thumbnail" data-figure="${esc(f.id)}" aria-label="放大查看：${esc(f.title)}"><span class="paper-thumb-image"><img src="${esc(f.assets.svg)}" alt="${esc(f.alt)}" loading="lazy"></span><span class="paper-thumb-title"><span class="figure-letter">${esc(f.letter)}</span>${esc(f.title)}<span aria-hidden="true">↗</span></span></button>`).join('')}</div>`;}
export function galleryMarkup(data,{filter='all'}={}){
 if(!data)return '<p class="paper-unavailable">图表数据暂时无法读取。排行榜不受影响，请刷新重试。</p>';
 const chosen=data.figures.filter(f=>filter==='all'||f.group===filter);
 return `<div class="paper-gallery-head"><div class="paper-stat-strip"><span><strong>${data.modelCount}</strong>完整模型</span><span><strong>${data.domainCount}</strong>分类领域</span><span><strong>${data.taskCount}</strong>分类任务</span><span><strong>${data.population.toLocaleString('en-US')}</strong>原始样本</span></div><div class="paper-gallery-actions"><a href="${esc(data.book)}" download>下载图表合集 · PDF ↗</a><a href="/research.json" download>图表数据 · JSON</a></div></div><div class="paper-filter" role="group" aria-label="图表分类">${Object.entries(filters).map(([id,title])=>`<button data-paper-filter="${id}" aria-pressed="${id===filter}">${title}</button>`).join('')}<span>${chosen.length} 张图</span></div><div class="paper-grid">${chosen.map(f=>`<article class="paper-card ${f.id==='profiles'?'paper-card-wide':''}" id="figure-${esc(f.id)}"><div class="paper-card-heading"><span class="figure-letter">${esc(f.letter)}</span><div><span class="section-kicker">${esc(f.kicker)}</span><h3>${esc(f.title)}</h3><p>${esc(f.description)}</p></div></div><button class="paper-art" data-figure="${esc(f.id)}" aria-label="放大查看：${esc(f.title)}"><img src="${esc(f.assets.svg)}" alt="${esc(f.alt)}" loading="${f.id==='profiles'?'eager':'lazy'}"><span class="paper-art-expand" aria-hidden="true">放大 ↗</span></button><div class="paper-card-bottom"><p class="figure-caveat">${esc(f.caveat)}</p>${actions(f)}${table(f)}</div></article>`).join('')}</div><div class="paper-provenance"><span class="section-kicker">METHOD & SOURCES</span><p>图表沿用冻结的评测结果与语料统计，不补填缺测，不将诊断项混入综合分。输入长度采用统一参考 tokenizer；问题去重只看查询文本；层级图的扇区宽度表示任务或指标个数，不表示样本量与计分权重。</p><a href="${esc(data.protocol)}" target="_blank" rel="noopener">复现方法与统计定义 ↗</a><a href="${esc(data.reference)}" target="_blank" rel="noopener">图形布局参考：T2AV-Compass ↗</a></div>`;
}
export function bindResearch(root){
 root.addEventListener('click',event=>{
  const zoom=event.target.closest('[data-figure-zoom]');if(!zoom)return;
  const content=root.getElementById('figureContent'),stage=content.querySelector('.figure-zoom-stage');
  stage.dataset.zoom=zoom.dataset.figureZoom;
  content.querySelectorAll('[data-figure-zoom]').forEach(b=>b.setAttribute('aria-pressed',String(b===zoom)));
 });
 // Native dialog handles focus trapping, Escape and focus restoration.
 root.getElementById('figureDetail').addEventListener('click',event=>{
  if(event.target===event.currentTarget){const r=event.currentTarget.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)event.currentTarget.close();}
 });
}
